### ISSUE TITLE
I used this library in my app : OpenCL-Z Android

### ISSUE THREAD

**Issue by robertwgh** [DenisMondon/material-design-library#7]
Denis, 

I used your library in my application OpenCL-Z Android.  It is released on Google Play now: https://play.google.com/store/apps/details?id=com.robertwgh.opencl_z_android

Thanks for your excellent work on this library. It is very easy to use, and looks nice, too.

By the way, I even kept the color scheme, because I think it looks so nice! :) 
Keep your great work going!

Regards,
Robert

**Comment by DenisMondon** [comment]
Whoaaa!!! 

Thanks a lot!
You're the first guy who released his app on Google Play because of me :D

I hope you will have a lot of downloads!
And don't forget to update the version of my library (in your build.gradle) to have the latest version!

By the way, I downloaded your app of course ;)

Thank you!

Regards,
Denis

**Comment by robertwgh** [comment]
WoW, the first?
It is really a honor, :)
I will definitely give the latest version a try.
Thanks for downloading my app. 

Hope more and more apps can take advantage of your excellent library. 

Best,
Robert
